### ISSUE TITLE
conda install --channel conda-forge ulmo  gives CondaHTTPError: HTTP 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by drf5n** [conda-forge/ulmo-feedstock#5] opened 2016-10-31 17:47 UTC
```
$ anaconda whoami
Using Anaconda API: https://api.anaconda.org
Anonymous User
$ conda --version
conda 4.2.11
$ conda install --channel conda-forge ulmo 
Fetching package metadata .......

CondaHTTPError: HTTP 401 UNAUTHORIZED
for url <https://conda.anaconda.org/conda-forge/osx-64/repodata.json>

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <http://conda.pydata.org/docs/config.html>.


```

I saw hints at https://github.com/conda/conda/issues/3399 and https://github.com/conda-forge/conda-forge.github.io/issues/226 to logout of anaconda but that didn't seem to solve my problem.

**Comment by ocefpaf** [comment] 2016-10-31 17:56
I am lost here :confused:

@msarahan have you seen this error? I cannot reproduce that.

**Comment by drf5n** [comment] 2016-10-31 18:03
A more verbose error log is here:

```
$ conda install --channel conda-forge ulmo -vv
DEBUG conda.cli.main:_main(143): verbosity set to 2
DEBUG conda.common.url:path_to_url(36): /Users/drf/anaconda/conda-bld converted to file:///Users/drf/anaconda/conda-bld
DEBUG conda.fetch:fetch_index(288): channel_urls=OrderedDict([(u'https://conda.anaconda.org/conda-forge/osx-64', (u'conda-forge', 0)), (u'https://conda.anaconda.org/conda-forge/noarch', (u'conda-forge', 0)), (u'https://repo.continuum.io/pkgs/free/osx-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/free/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/pro/osx-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/pro/noarch', (u'defaults', 1))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(155): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG requests.packages.urllib3.util.retry:from_int(155): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG requests.packages.urllib3.util.retry:from_int(155): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.fetch:fetch_repodata(86): Opening repodata cache for https://conda.anaconda.org/conda-forge/osx-64 at /Users/drf/anaconda/pkgs/cache/fdfa8174.json
DEBUG conda.fetch:fetch_repodata(86): Opening repodata cache for https://conda.anaconda.org/conda-forge/noarch at /Users/drf/anaconda/pkgs/cache/36521c4e.json
DEBUG requests.packages.urllib3.util.retry:from_int(155): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.fetch:fetch_repodata(86): Opening repodata cache for https://repo.continuum.io/pkgs/free/osx-64 at /Users/drf/anaconda/pkgs/cache/840cf1fb.json
DEBUG requests.packages.urllib3.util.retry:from_int(155): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.fetch:fetch_repodata(86): Opening repodata cache for https://repo.continuum.io/pkgs/free/noarch at /Users/drf/anaconda/pkgs/cache/524e4676.json
DEBUG requests.packages.urllib3.util.retry:from_int(155): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.fetch:fetch_repodata(86): Opening repodata cache for https://repo.continuum.io/pkgs/pro/osx-64 at /Users/drf/anaconda/pkgs/cache/ad7eda34.json
DEBUG conda.fetch:fetch_repodata(86): Opening repodata cache for https://repo.continuum.io/pkgs/pro/noarch at /Users/drf/anaconda/pkgs/cache/f1a0ac49.json
INFO requests.packages.urllib3.connectionpool:_new_conn(735): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(735): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(735): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(735): Starting new HTTPS connection (1): repo.continuum.io
INFO requests.packages.urllib3.connectionpool:_new_conn(735): Starting new HTTPS connection (1): conda.anaconda.org
INFO requests.packages.urllib3.connectionpool:_new_conn(735): Starting new HTTPS connection (1): conda.anaconda.org
DEBUG requests.packages.urllib3.connectionpool:_make_request(383): "GET /pkgs/pro/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.fetch:fetch_repodata(118): 
> GET /pkgs/pro/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.2.11 requests/2.7.0 CPython/2.7.11 Darwin/14.5.0 OSX/10.10.5
> Accept: */*
> Accept-Encoding: identity
> Authorization: Basic YW5vbnltb3VzOnVzZXJAc2l0ZQ==
> Connection: keep-alive
> If-Modified-Since: Fri, 12 Feb 2016 07:52:34 GMT
> If-None-Match: "56bd8f42-46"

< HTTPS 304 Not Modified
> cache-control: public, max-age=300
> cf-cache-status: HIT
> cf-ray: 2fa904316b7023ea-IAD
> connection: keep-alive
> date: Mon, 31 Oct 2016 18:02:09 GMT
> etag: "56bd8f42-46"
> expires: Mon, 31 Oct 2016 18:07:09 GMT
> last-modified: Fri, 12 Feb 2016 07:52:34 GMT
> server: cloudflare-nginx
> set-cookie: __cfduid=d522f1572dd7ccac4ea70de21400881771477936929; expires=Tue, 31-Oct-17 18:02:09 GMT; path=/; domain=.continuum.io; HttpOnly
> vary: Accept-Encoding


DEBUG requests.packages.urllib3.connectionpool:_make_request(383): "GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG conda.fetch:fetch_repodata(118): 
> GET /pkgs/free/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.2.11 requests/2.7.0 CPython/2.7.11 Darwin/14.5.0 OSX/10.10.5
> Accept: */*
> Accept-Encoding: identity
> Authorization: Basic YW5vbnltb3VzOnVzZXJAc2l0ZQ==
> Connection: keep-alive
> If-Modified-Since: Wed, 19 Oct 2016 01:33:38 GMT
> If-None-Match: "5806cd72-3f4"

< HTTPS 304 Not Modified
> cache-control: public, max-age=300
> cf-cache-status: HIT
> cf-ray: 2fa904317e0a5789-IAD
> connection: keep-alive
> date: Mon, 31 Oct 2016 18:02:09 GMT
> etag: "5806cd72-3f4"
> expires: Mon, 31 Oct 2016 18:07:09 GMT
> last-modified: Wed, 19 Oct 2016 01:33:38 GMT
> server: cloudflare-nginx
> set-cookie: __cfduid=d6a3e4a84d085fedcf1b9611ebe267dfe1477936929; expires=Tue, 31-Oct-17 18:02:09 GMT; path=/; domain=.continuum.io; HttpOnly
> vary: Accept-Encoding


.DEBUG requests.packages.urllib3.connectionpool:_make_request(383): "GET /pkgs/pro/osx-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.fetch:fetch_repodata(118): 
> GET /pkgs/pro/osx-64/repodata.json.bz2 HTTPS
> User-Agent: conda/4.2.11 requests/2.7.0 CPython/2.7.11 Darwin/14.5.0 OSX/10.10.5
> Accept: */*
> Accept-Encoding: identity
> Authorization: Basic YW5vbnltb3VzOnVzZXJAc2l0ZQ==
> Connection: keep-alive
> If-Modified-Since: Fri, 28 Oct 2016 20:51:35 GMT
> If-None-Match: "5813ba57-5659"

< HTTPS 304 Not Modified
> cache-control: public, max-age=300
> cf-cache-status: HIT
> cf-ray: 2fa904318d56241a-IAD
> connection: keep-alive
> date: Mon, 31 Oct 2016 18:02:09 GMT
> etag: "5813ba57-5659"
> expires: Mon, 31 Oct 2016 18:07:09 GMT
> last-modified: Fri, 28 Oct 2016 20:51:35 GMT
> server: cloudflare-nginx
> set-cookie: __cfduid=d79a62b9a7581337bc12eb7949a7c87581477936929; expires=Tue, 31-Oct-17 18:02:09 GMT; path=/; domain=.continuum.io; HttpOnly
> vary: Accept-Encoding


.DEBUG requests.packages.urllib3.connectionpool:_make_request(383): "GET /conda-forge/noarch/repodata.json HTTP/1.1" 401 13
DEBUG conda.fetch:fetch_repodata(118): 
> GET /conda-forge/noarch/repodata.json HTTPS
> User-Agent: conda/4.2.11 requests/2.7.0 CPython/2.7.11 Darwin/14.5.0 OSX/10.10.5
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Authorization: Basic YW5vbnltb3VzOnVzZXJAc2l0ZQ==
> Connection: keep-alive
> Content-Type: application/json

< HTTPS 401 UNAUTHORIZED
> connection: keep-alive
> content-length: 13
> content-type: text/html; charset=utf-8
> date: Mon, 31 Oct 2016 18:02:09 GMT
> license_expired: False
> license_valid: True
> server: nginx/1.10.1
> set-cookie: session=eyJfaWQiOnsiIGIiOiJORE5oTURkaVkyTTROV001TURSa09UYzNNalpsTURGak1qZzJOV1l5TURVPSJ9fQ.CvkYoQ.20WSQVEQn-9tzPKDkp0O0Ad4xUQ; Domain=.anaconda.org; HttpOnly; Path=/

Invalid Token

DEBUG requests.packages.urllib3.connectionpool:_make_request(383): "GET /conda-forge/osx-64/repodata.json HTTP/1.1" 401 13
DEBUG conda.fetch:fetch_repodata(118): 
> GET /conda-forge/osx-64/repodata.json HTTPS
> User-Agent: conda/4.2.11 requests/2.7.0 CPython/2.7.11 Darwin/14.5.0 OSX/10.10.5
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Authorization: Basic YW5vbnltb3VzOnVzZXJAc2l0ZQ==
> Connection: keep-alive
> Content-Type: application/json

< HTTPS 401 UNAUTHORIZED
> connection: keep-alive
> content-length: 13
> content-type: text/html; charset=utf-8
> date: Mon, 31 Oct 2016 18:02:09 GMT
> license_expired: False
> license_valid: True
> server: nginx/1.10.1
> set-cookie: session=eyJfaWQiOnsiIGIiOiJORE5oTURkaVkyTTROV001TURSa09UYzNNalpsTURGak1qZzJOV1l5TURVPSJ9fQ.CvkYoQ.20WSQVEQn-9tzPKDkp0O0Ad4xUQ; Domain=.anaconda.org; HttpOnly; Path=/

Invalid Token

DEBUG requests.packages.urllib3.connectionpool:_make_request(383): "GET /pkgs/free/osx-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.fetch:fetch_repodata(118): 
> GET /pkgs/free/osx-64/repodata.json.bz2 HTTPS
> User-Agent: conda/4.2.11 requests/2.7.0 CPython/2.7.11 Darwin/14.5.0 OSX/10.10.5
> Accept: */*
> Accept-Encoding: identity
> Authorization: Basic YW5vbnltb3VzOnVzZXJAc2l0ZQ==
> Connection: keep-alive
> If-Modified-Since: Fri, 28 Oct 2016 20:51:24 GMT
> If-None-Match: "5813ba4c-4f0de"

< HTTPS 304 Not Modified
> cache-control: public, max-age=300
> cf-cache-status: HIT
> cf-ray: 2fa904378d975759-IAD
> connection: keep-alive
> date: Mon, 31 Oct 2016 18:02:10 GMT
> etag: "5813ba4c-4f0de"
> expires: Mon, 31 Oct 2016 18:07:10 GMT
> last-modified: Fri, 28 Oct 2016 20:51:24 GMT
> server: cloudflare-nginx
> set-cookie: __cfduid=dc5612aa9a91a5b215280b9cf03a8bf0e1477936930; expires=Tue, 31-Oct-17 18:02:10 GMT; path=/; domain=.continuum.io; HttpOnly
> vary: Accept-Encoding


.An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(27): overtaking stderr and stdout
INFO conda.common.io:captured(33): stderr and stdout yielded back
Current conda install:

               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.14.1
         python version : 2.7.11.final.0
       requests version : 2.7.0
       root environment : /Users/drf/anaconda  (writable)
    default environment : /Users/drf/anaconda
       envs directories : /Users/drf/anaconda/envs
          package cache : /Users/drf/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/drf/.condarc
           offline mode : False



`$ /Users/drf/anaconda/bin/conda install --channel conda-forge ulmo -vv`




    Traceback (most recent call last):
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/drf/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result
        return self.__get_result()
      File "/Users/drf/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 220, in fetch_repodata
        e.response.reason)
    CondaHTTPError: HTTP 401 UNAUTHORIZED
    for url <https://conda.anaconda.org/conda-forge/osx-64/repodata.json>

    The remote server has indicated you are using invalid credentials for this channel.

    If the remote site is anaconda.org or follows the Anaconda Server API, you
    will need to
      (a) login to the site with `anaconda login`, or
      (b) provide conda with a valid token directly.

    Further configuration help can be found at <http://conda.pydata.org/docs/config.html>.


$ 

```

**Comment by msarahan** [comment] 2016-10-31 18:07
Nope, haven't seen this. Please file an issue on the conda issue tracker

**Comment by drf5n** [comment] 2016-10-31 18:15
Thanks. I added to the https://github.com/conda/conda/issues/3399 issue.

**Comment by dharhas** [comment] 2016-10-31 18:18
ok closing this since I don't think its ulmo related. I can reopen if it is.

**Closed as completed by dharhas** 2016-10-31 18:18 UTC
